# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/create_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_create_window(object):
    def setupUi(self, create_window):
        create_window.setObjectName("create_window")
        create_window.setWindowModality(QtCore.Qt.ApplicationModal)
        create_window.resize(1186, 816)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        create_window.setPalette(palette)
        create_window.setAutoFillBackground(True)
        create_window.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(create_window)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(create_window)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.title = QtWidgets.QLineEdit(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.title.setPalette(palette)
        self.title.setAutoFillBackground(True)
        self.title.setFrame(False)
        self.title.setObjectName("title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.title)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.alt_title = QtWidgets.QLineEdit(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.alt_title.setPalette(palette)
        self.alt_title.setAutoFillBackground(True)
        self.alt_title.setFrame(False)
        self.alt_title.setObjectName("alt_title")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.alt_title)
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(15)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_30 = QtWidgets.QLabel(self.frame_14)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 0, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_14)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 0, 0, 1, 1)
        self.genres_no_list = QtWidgets.QListWidget(self.frame_14)
        self.genres_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.genres_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.genres_no_list.setObjectName("genres_no_list")
        self.gridLayout_4.addWidget(self.genres_no_list, 2, 1, 1, 1)
        self.genres_yes_list = QtWidgets.QListWidget(self.frame_14)
        self.genres_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.genres_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.genres_yes_list.setObjectName("genres_yes_list")
        self.gridLayout_4.addWidget(self.genres_yes_list, 2, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_14)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.genres_yes = QtWidgets.QLineEdit(self.frame_7)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.genres_yes.setPalette(palette)
        self.genres_yes.setAutoFillBackground(True)
        self.genres_yes.setFrame(False)
        self.genres_yes.setObjectName("genres_yes")
        self.horizontalLayout_11.addWidget(self.genres_yes)
        self.genres_yes_button = QtWidgets.QToolButton(self.frame_7)
        self.genres_yes_button.setObjectName("genres_yes_button")
        self.horizontalLayout_11.addWidget(self.genres_yes_button)
        self.gridLayout_4.addWidget(self.frame_7, 1, 0, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.genres_no = QtWidgets.QLineEdit(self.frame_15)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.genres_no.setPalette(palette)
        self.genres_no.setAutoFillBackground(True)
        self.genres_no.setFrame(False)
        self.genres_no.setObjectName("genres_no")
        self.horizontalLayout_12.addWidget(self.genres_no)
        self.genres_no_button = QtWidgets.QToolButton(self.frame_15)
        self.genres_no_button.setObjectName("genres_no_button")
        self.horizontalLayout_12.addWidget(self.genres_no_button)
        self.gridLayout_4.addWidget(self.frame_15, 1, 1, 1, 1)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.frame_14)
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setObjectName("label_32")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.frame_17 = QtWidgets.QFrame(self.frame)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(15)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tags_yes_list = QtWidgets.QListWidget(self.frame_17)
        self.tags_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.tags_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tags_yes_list.setObjectName("tags_yes_list")
        self.gridLayout_5.addWidget(self.tags_yes_list, 2, 0, 1, 1)
        self.tags_no_list = QtWidgets.QListWidget(self.frame_17)
        self.tags_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.tags_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tags_no_list.setObjectName("tags_no_list")
        self.gridLayout_5.addWidget(self.tags_no_list, 2, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_17)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_17)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 0, 1, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.frame_17)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tags_yes = QtWidgets.QLineEdit(self.frame_16)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tags_yes.setPalette(palette)
        self.tags_yes.setAutoFillBackground(True)
        self.tags_yes.setFrame(False)
        self.tags_yes.setObjectName("tags_yes")
        self.horizontalLayout_13.addWidget(self.tags_yes)
        self.tags_yes_button = QtWidgets.QToolButton(self.frame_16)
        self.tags_yes_button.setObjectName("tags_yes_button")
        self.horizontalLayout_13.addWidget(self.tags_yes_button)
        self.gridLayout_5.addWidget(self.frame_16, 1, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tags_no = QtWidgets.QLineEdit(self.frame_19)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tags_no.setPalette(palette)
        self.tags_no.setAutoFillBackground(True)
        self.tags_no.setFrame(False)
        self.tags_no.setObjectName("tags_no")
        self.horizontalLayout_14.addWidget(self.tags_no)
        self.tags_no_button = QtWidgets.QToolButton(self.frame_19)
        self.tags_no_button.setObjectName("tags_no_button")
        self.horizontalLayout_14.addWidget(self.tags_no_button)
        self.gridLayout_5.addWidget(self.frame_19, 1, 1, 1, 1)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.frame_17)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(create_window)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.order = QtWidgets.QLineEdit(self.frame_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.order.setPalette(palette)
        self.order.setAutoFillBackground(True)
        self.order.setFrame(False)
        self.order.setObjectName("order")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.order)
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.series_bleh = QtWidgets.QFrame(self.frame_2)
        self.series_bleh.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.series_bleh.setFrameShadow(QtWidgets.QFrame.Raised)
        self.series_bleh.setObjectName("series_bleh")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.series_bleh)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_8 = QtWidgets.QFrame(self.series_bleh)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.series = QtWidgets.QLineEdit(self.frame_8)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.series.setPalette(palette)
        self.series.setAutoFillBackground(True)
        self.series.setFrame(False)
        self.series.setObjectName("series")
        self.horizontalLayout_2.addWidget(self.series)
        self.series_button = QtWidgets.QToolButton(self.frame_8)
        self.series_button.setObjectName("series_button")
        self.horizontalLayout_2.addWidget(self.series_button)
        self.verticalLayout.addWidget(self.frame_8)
        self.series_list = QtWidgets.QListWidget(self.series_bleh)
        self.series_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.series_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.series_list.setAlternatingRowColors(False)
        self.series_list.setObjectName("series_list")
        self.verticalLayout.addWidget(self.series_list)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.series_bleh)
        self.frame_18 = QtWidgets.QFrame(self.frame_2)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(15)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_21 = QtWidgets.QFrame(self.frame_18)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.actors_no = QtWidgets.QLineEdit(self.frame_21)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.actors_no.setPalette(palette)
        self.actors_no.setAutoFillBackground(True)
        self.actors_no.setFrame(False)
        self.actors_no.setObjectName("actors_no")
        self.horizontalLayout_16.addWidget(self.actors_no)
        self.actors_no_button = QtWidgets.QToolButton(self.frame_21)
        self.actors_no_button.setObjectName("actors_no_button")
        self.horizontalLayout_16.addWidget(self.actors_no_button)
        self.gridLayout_6.addWidget(self.frame_21, 1, 1, 1, 1)
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.actors_yes = QtWidgets.QLineEdit(self.frame_20)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.actors_yes.setPalette(palette)
        self.actors_yes.setAutoFillBackground(True)
        self.actors_yes.setFrame(False)
        self.actors_yes.setObjectName("actors_yes")
        self.horizontalLayout_15.addWidget(self.actors_yes)
        self.actors_yes_button = QtWidgets.QToolButton(self.frame_20)
        self.actors_yes_button.setObjectName("actors_yes_button")
        self.horizontalLayout_15.addWidget(self.actors_yes_button)
        self.gridLayout_6.addWidget(self.frame_20, 1, 0, 1, 1)
        self.actors_no_list = QtWidgets.QListWidget(self.frame_18)
        self.actors_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.actors_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.actors_no_list.setObjectName("actors_no_list")
        self.gridLayout_6.addWidget(self.actors_no_list, 2, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.frame_18)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 0, 1, 1, 1)
        self.actors_yes_list = QtWidgets.QListWidget(self.frame_18)
        self.actors_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.actors_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.actors_yes_list.setObjectName("actors_yes_list")
        self.gridLayout_6.addWidget(self.actors_yes_list, 2, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_18)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 0, 0, 1, 1)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.frame_18)
        self.label_35 = QtWidgets.QLabel(self.frame_2)
        self.label_35.setObjectName("label_35")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.notes = QtWidgets.QTextEdit(self.frame_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.notes.setPalette(palette)
        self.notes.setObjectName("notes")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.notes)
        self.gridLayout.addWidget(self.frame_2, 2, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(create_window)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.year = QtWidgets.QLineEdit(self.frame_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.year.setPalette(palette)
        self.year.setAutoFillBackground(True)
        self.year.setFrame(False)
        self.year.setObjectName("year")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.year)
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_18.setPalette(palette)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.frame_22 = QtWidgets.QFrame(self.frame_3)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_13 = QtWidgets.QFrame(self.frame_22)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.country = QtWidgets.QLineEdit(self.frame_13)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.country.setPalette(palette)
        self.country.setAutoFillBackground(True)
        self.country.setFrame(False)
        self.country.setObjectName("country")
        self.horizontalLayout_10.addWidget(self.country)
        self.country_button = QtWidgets.QToolButton(self.frame_13)
        self.country_button.setObjectName("country_button")
        self.horizontalLayout_10.addWidget(self.country_button)
        self.verticalLayout_6.addWidget(self.frame_13)
        self.country_list = QtWidgets.QListWidget(self.frame_22)
        self.country_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.country_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.country_list.setObjectName("country_list")
        self.verticalLayout_6.addWidget(self.country_list)
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_22)
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.frame_12 = QtWidgets.QFrame(self.frame_3)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_23 = QtWidgets.QFrame(self.frame_12)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.language = QtWidgets.QLineEdit(self.frame_23)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.language.setPalette(palette)
        self.language.setAutoFillBackground(True)
        self.language.setFrame(False)
        self.language.setObjectName("language")
        self.horizontalLayout_5.addWidget(self.language)
        self.language_button = QtWidgets.QToolButton(self.frame_23)
        self.language_button.setObjectName("language_button")
        self.horizontalLayout_5.addWidget(self.language_button)
        self.verticalLayout_4.addWidget(self.frame_23)
        self.language_list = QtWidgets.QListWidget(self.frame_12)
        self.language_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.language_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.language_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.language_list.setObjectName("language_list")
        self.verticalLayout_4.addWidget(self.language_list)
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.frame_12)
        self.label_22 = QtWidgets.QLabel(self.frame_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_22.setPalette(palette)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.subtitles = QtWidgets.QFrame(self.frame_3)
        self.subtitles.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subtitles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.subtitles.setObjectName("subtitles")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.subtitles)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.subtitles_yes = QtWidgets.QRadioButton(self.subtitles)
        self.subtitles_yes.setObjectName("subtitles_yes")
        self.horizontalLayout_7.addWidget(self.subtitles_yes)
        self.subtitles_no = QtWidgets.QRadioButton(self.subtitles)
        self.subtitles_no.setObjectName("subtitles_no")
        self.horizontalLayout_7.addWidget(self.subtitles_no)
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.subtitles)
        self.label_28 = QtWidgets.QLabel(self.frame_3)
        self.label_28.setObjectName("label_28")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.plot = QtWidgets.QTextEdit(self.frame_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.plot.setPalette(palette)
        self.plot.setObjectName("plot")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.plot)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_3.setItem(7, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.frame_24 = QtWidgets.QFrame(self.frame_3)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(20)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.submit = QtWidgets.QPushButton(self.frame_24)
        self.submit.setMinimumSize(QtCore.QSize(50, 50))
        self.submit.setStyleSheet("background:rgb(0, 255, 0);")
        self.submit.setAutoDefault(False)
        self.submit.setObjectName("submit")
        self.horizontalLayout_17.addWidget(self.submit)
        self.clear = QtWidgets.QPushButton(self.frame_24)
        self.clear.setMinimumSize(QtCore.QSize(50, 50))
        self.clear.setStyleSheet("background:rgb(255, 0, 0);")
        self.clear.setAutoDefault(False)
        self.clear.setObjectName("clear")
        self.horizontalLayout_17.addWidget(self.clear)
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.frame_24)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.gridLayout.addWidget(self.frame_3, 2, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(create_window)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_31 = QtWidgets.QLabel(self.frame_4)
        self.label_31.setObjectName("label_31")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.rating = QtWidgets.QFrame(self.frame_4)
        self.rating.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rating.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rating.setObjectName("rating")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.rating)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_6 = QtWidgets.QFrame(self.rating)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rating_none = QtWidgets.QRadioButton(self.frame_6)
        self.rating_none.setObjectName("rating_none")
        self.horizontalLayout.addWidget(self.rating_none)
        self.rating_1 = QtWidgets.QRadioButton(self.frame_6)
        self.rating_1.setObjectName("rating_1")
        self.horizontalLayout.addWidget(self.rating_1)
        self.rating_2 = QtWidgets.QRadioButton(self.frame_6)
        self.rating_2.setObjectName("rating_2")
        self.horizontalLayout.addWidget(self.rating_2)
        self.rating_3 = QtWidgets.QRadioButton(self.frame_6)
        self.rating_3.setObjectName("rating_3")
        self.horizontalLayout.addWidget(self.rating_3)
        self.rating_4 = QtWidgets.QRadioButton(self.frame_6)
        self.rating_4.setObjectName("rating_4")
        self.horizontalLayout.addWidget(self.rating_4)
        self.rating_5 = QtWidgets.QRadioButton(self.frame_6)
        self.rating_5.setObjectName("rating_5")
        self.horizontalLayout.addWidget(self.rating_5)
        self.horizontalLayout_9.addWidget(self.frame_6)
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rating)
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_16.setPalette(palette)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.media_type = QtWidgets.QLineEdit(self.frame_11)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.media_type.setPalette(palette)
        self.media_type.setAutoFillBackground(True)
        self.media_type.setFrame(False)
        self.media_type.setObjectName("media_type")
        self.horizontalLayout_8.addWidget(self.media_type)
        self.media_type_button = QtWidgets.QToolButton(self.frame_11)
        self.media_type_button.setObjectName("media_type_button")
        self.horizontalLayout_8.addWidget(self.media_type_button)
        self.verticalLayout_5.addWidget(self.frame_11)
        self.media_type_list = QtWidgets.QListWidget(self.frame_9)
        self.media_type_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.media_type_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.media_type_list.setObjectName("media_type_list")
        self.verticalLayout_5.addWidget(self.media_type_list)
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_9)
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_17.setPalette(palette)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.animated = QtWidgets.QFrame(self.frame_4)
        self.animated.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.animated.setFrameShadow(QtWidgets.QFrame.Raised)
        self.animated.setObjectName("animated")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.animated)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.animated_yes = QtWidgets.QRadioButton(self.animated)
        self.animated_yes.setObjectName("animated_yes")
        self.horizontalLayout_4.addWidget(self.animated_yes)
        self.animated_no = QtWidgets.QRadioButton(self.animated)
        self.animated_no.setObjectName("animated_no")
        self.horizontalLayout_4.addWidget(self.animated_no)
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.animated)
        self.label_26 = QtWidgets.QLabel(self.frame_4)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.series_bleh_2 = QtWidgets.QFrame(self.frame_4)
        self.series_bleh_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.series_bleh_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.series_bleh_2.setObjectName("series_bleh_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.series_bleh_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.series_bleh_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.studio = QtWidgets.QLineEdit(self.frame_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.studio.setPalette(palette)
        self.studio.setAutoFillBackground(True)
        self.studio.setFrame(False)
        self.studio.setObjectName("studio")
        self.horizontalLayout_3.addWidget(self.studio)
        self.studio_button = QtWidgets.QToolButton(self.frame_5)
        self.studio_button.setObjectName("studio_button")
        self.horizontalLayout_3.addWidget(self.studio_button)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.studio_list = QtWidgets.QListWidget(self.series_bleh_2)
        self.studio_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.studio_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.studio_list.setAlternatingRowColors(False)
        self.studio_list.setObjectName("studio_list")
        self.verticalLayout_2.addWidget(self.studio_list)
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.series_bleh_2)
        self.label_25 = QtWidgets.QLabel(self.frame_4)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.series_bleh_3 = QtWidgets.QFrame(self.frame_4)
        self.series_bleh_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.series_bleh_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.series_bleh_3.setObjectName("series_bleh_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.series_bleh_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.series_bleh_3)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.director = QtWidgets.QLineEdit(self.frame_10)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.director.setPalette(palette)
        self.director.setAutoFillBackground(True)
        self.director.setFrame(False)
        self.director.setObjectName("director")
        self.horizontalLayout_6.addWidget(self.director)
        self.director_button = QtWidgets.QToolButton(self.frame_10)
        self.director_button.setObjectName("director_button")
        self.horizontalLayout_6.addWidget(self.director_button)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.director_list = QtWidgets.QListWidget(self.series_bleh_3)
        self.director_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.director_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.director_list.setAlternatingRowColors(False)
        self.director_list.setObjectName("director_list")
        self.verticalLayout_3.addWidget(self.director_list)
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.series_bleh_3)
        self.gridLayout.addWidget(self.frame_4, 1, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(create_window)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.imdb = QtWidgets.QWidget()
        self.imdb.setAutoFillBackground(True)
        self.imdb.setObjectName("imdb")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.imdb)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.imdb_scan = QtWidgets.QPushButton(self.imdb)
        self.imdb_scan.setMinimumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.imdb_scan.setFont(font)
        self.imdb_scan.setAutoDefault(False)
        self.imdb_scan.setObjectName("imdb_scan")
        self.verticalLayout_7.addWidget(self.imdb_scan)
        self.imdb_0 = QtWidgets.QPushButton(self.imdb)
        self.imdb_0.setMinimumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.imdb_0.setFont(font)
        self.imdb_0.setAutoDefault(False)
        self.imdb_0.setObjectName("imdb_0")
        self.verticalLayout_7.addWidget(self.imdb_0)
        self.imdb_1 = QtWidgets.QPushButton(self.imdb)
        self.imdb_1.setMinimumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.imdb_1.setFont(font)
        self.imdb_1.setAutoDefault(False)
        self.imdb_1.setObjectName("imdb_1")
        self.verticalLayout_7.addWidget(self.imdb_1)
        self.imdb_2 = QtWidgets.QPushButton(self.imdb)
        self.imdb_2.setMinimumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.imdb_2.setFont(font)
        self.imdb_2.setAutoDefault(False)
        self.imdb_2.setObjectName("imdb_2")
        self.verticalLayout_7.addWidget(self.imdb_2)
        self.tabWidget.addTab(self.imdb, "")
        self.mal = QtWidgets.QWidget()
        self.mal.setAutoFillBackground(True)
        self.mal.setObjectName("mal")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.mal)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.mal_scan = QtWidgets.QPushButton(self.mal)
        self.mal_scan.setMinimumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mal_scan.setFont(font)
        self.mal_scan.setAutoDefault(False)
        self.mal_scan.setObjectName("mal_scan")
        self.verticalLayout_9.addWidget(self.mal_scan)
        self.mal_3 = QtWidgets.QPushButton(self.mal)
        self.mal_3.setMinimumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mal_3.setFont(font)
        self.mal_3.setAutoDefault(False)
        self.mal_3.setObjectName("mal_3")
        self.verticalLayout_9.addWidget(self.mal_3)
        self.mal_1 = QtWidgets.QPushButton(self.mal)
        self.mal_1.setMinimumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mal_1.setFont(font)
        self.mal_1.setAutoDefault(False)
        self.mal_1.setObjectName("mal_1")
        self.verticalLayout_9.addWidget(self.mal_1)
        self.mal_2 = QtWidgets.QPushButton(self.mal)
        self.mal_2.setMinimumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mal_2.setFont(font)
        self.mal_2.setAutoDefault(False)
        self.mal_2.setObjectName("mal_2")
        self.verticalLayout_9.addWidget(self.mal_2)
        self.tabWidget.addTab(self.mal, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 3, 1)

        self.retranslateUi(create_window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(create_window)

    def retranslateUi(self, create_window):
        _translate = QtCore.QCoreApplication.translate
        create_window.setWindowTitle(_translate("create_window", "Create New Media Entry"))
        self.label.setText(_translate("create_window", "Title"))
        self.label_2.setText(_translate("create_window", "Alternate Title"))
        self.label_24.setText(_translate("create_window", "Genres"))
        self.label_30.setText(_translate("create_window", "Unapplied"))
        self.label_29.setText(_translate("create_window", "Applied"))
        self.genres_yes_button.setText(_translate("create_window", "..."))
        self.genres_no_button.setText(_translate("create_window", "..."))
        self.label_32.setText(_translate("create_window", "Tags"))
        self.label_34.setText(_translate("create_window", "Applied"))
        self.label_33.setText(_translate("create_window", "Unapplied"))
        self.tags_yes_button.setText(_translate("create_window", "..."))
        self.tags_no_button.setText(_translate("create_window", "..."))
        self.label_3.setText(_translate("create_window", "Series"))
        self.label_4.setText(_translate("create_window", "Order"))
        self.label_27.setText(_translate("create_window", "Actors"))
        self.series_button.setText(_translate("create_window", "..."))
        self.actors_no_button.setText(_translate("create_window", "..."))
        self.actors_yes_button.setText(_translate("create_window", "..."))
        self.label_36.setText(_translate("create_window", "Unapplied"))
        self.label_37.setText(_translate("create_window", "Applied"))
        self.label_35.setText(_translate("create_window", "Notes"))
        self.label_23.setText(_translate("create_window", "Release \n"
"Year"))
        self.label_18.setText(_translate("create_window", "Country of \n"
"Origin"))
        self.country_button.setText(_translate("create_window", "..."))
        self.label_20.setText(_translate("create_window", "Languages"))
        self.language_button.setText(_translate("create_window", "..."))
        self.label_22.setText(_translate("create_window", "Subtitles"))
        self.subtitles_yes.setText(_translate("create_window", "Yes"))
        self.subtitles_no.setText(_translate("create_window", "No"))
        self.label_28.setText(_translate("create_window", "Plot"))
        self.submit.setText(_translate("create_window", "Submit"))
        self.clear.setText(_translate("create_window", "Clear"))
        self.label_5.setText(_translate("create_window", "Note: all fields in green are REQUIRED fields"))
        self.label_31.setText(_translate("create_window", "Rating"))
        self.rating_none.setText(_translate("create_window", "None"))
        self.rating_1.setText(_translate("create_window", "1"))
        self.rating_2.setText(_translate("create_window", "2"))
        self.rating_3.setText(_translate("create_window", "3"))
        self.rating_4.setText(_translate("create_window", "4"))
        self.rating_5.setText(_translate("create_window", "5"))
        self.label_16.setText(_translate("create_window", "Media Type"))
        self.media_type_button.setText(_translate("create_window", "..."))
        self.label_17.setText(_translate("create_window", "Animated?"))
        self.animated_yes.setText(_translate("create_window", "Yes"))
        self.animated_no.setText(_translate("create_window", "No"))
        self.label_26.setText(_translate("create_window", "Studio"))
        self.studio_button.setText(_translate("create_window", "..."))
        self.label_25.setText(_translate("create_window", "Director"))
        self.director_button.setText(_translate("create_window", "..."))
        self.imdb_scan.setText(_translate("create_window", "Scan IMDb"))
        self.imdb_0.setText(_translate("create_window", "NULL"))
        self.imdb_1.setText(_translate("create_window", "NULL"))
        self.imdb_2.setText(_translate("create_window", "NULL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.imdb), _translate("create_window", "IMDB"))
        self.mal_scan.setText(_translate("create_window", "Scan MyAnimeList"))
        self.mal_3.setText(_translate("create_window", "NULL"))
        self.mal_1.setText(_translate("create_window", "NULL"))
        self.mal_2.setText(_translate("create_window", "NULL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mal), _translate("create_window", "My Anime List"))
