# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/create_delete_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_create_delete_window(object):
    def setupUi(self, create_delete_window):
        create_delete_window.setObjectName("create_delete_window")
        create_delete_window.resize(778, 699)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        create_delete_window.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(create_delete_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tab.setPalette(palette)
        self.tab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab.setObjectName("tab")
        self.create = QtWidgets.QWidget()
        self.create.setAutoFillBackground(True)
        self.create.setObjectName("create")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.create)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.create)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setObjectName("label_32")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.genres_create = QtWidgets.QTextEdit(self.frame)
        self.genres_create.setTabChangesFocus(True)
        self.genres_create.setObjectName("genres_create")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.genres_create)
        self.tags_create = QtWidgets.QTextEdit(self.frame)
        self.tags_create.setTabChangesFocus(True)
        self.tags_create.setObjectName("tags_create")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tags_create)
        self.actors_create = QtWidgets.QTextEdit(self.frame)
        self.actors_create.setTabChangesFocus(True)
        self.actors_create.setObjectName("actors_create")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.actors_create)
        self.series_create = QtWidgets.QTextEdit(self.frame)
        self.series_create.setTabChangesFocus(True)
        self.series_create.setObjectName("series_create")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.series_create)
        self.director_create = QtWidgets.QTextEdit(self.frame)
        self.director_create.setTabChangesFocus(True)
        self.director_create.setObjectName("director_create")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.director_create)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.create)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_26 = QtWidgets.QLabel(self.frame_4)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.studio_create = QtWidgets.QTextEdit(self.frame_4)
        self.studio_create.setTabChangesFocus(True)
        self.studio_create.setObjectName("studio_create")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.studio_create)
        self.media_type_create = QtWidgets.QTextEdit(self.frame_4)
        self.media_type_create.setTabChangesFocus(True)
        self.media_type_create.setObjectName("media_type_create")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.media_type_create)
        self.submit_create = QtWidgets.QPushButton(self.frame_4)
        self.submit_create.setMinimumSize(QtCore.QSize(50, 50))
        self.submit_create.setObjectName("submit_create")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.submit_create)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_4.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.country_create = QtWidgets.QTextEdit(self.frame_4)
        self.country_create.setTabChangesFocus(True)
        self.country_create.setObjectName("country_create")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.country_create)
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.language_create = QtWidgets.QTextEdit(self.frame_4)
        self.language_create.setTabChangesFocus(True)
        self.language_create.setObjectName("language_create")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.language_create)
        self.label_20 = QtWidgets.QLabel(self.frame_4)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.gridLayout_2.addWidget(self.frame_4, 0, 1, 1, 1)
        self.tab.addTab(self.create, "")
        self.delete = QtWidgets.QWidget()
        self.delete.setAutoFillBackground(True)
        self.delete.setObjectName("delete")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.delete)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_37 = QtWidgets.QFrame(self.delete)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_37.setObjectName("frame_37")
        self.formLayout_8 = QtWidgets.QFormLayout(self.frame_37)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_47 = QtWidgets.QLabel(self.frame_37)
        self.label_47.setObjectName("label_47")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.frame_38 = QtWidgets.QFrame(self.frame_37)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_38)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(15)
        self.gridLayout_8.setVerticalSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tags_yes_list = QtWidgets.QListWidget(self.frame_38)
        self.tags_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.tags_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tags_yes_list.setObjectName("tags_yes_list")
        self.gridLayout_8.addWidget(self.tags_yes_list, 2, 0, 1, 1)
        self.tags_no_list = QtWidgets.QListWidget(self.frame_38)
        self.tags_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.tags_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tags_no_list.setObjectName("tags_no_list")
        self.gridLayout_8.addWidget(self.tags_no_list, 2, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.frame_38)
        self.label_48.setObjectName("label_48")
        self.gridLayout_8.addWidget(self.label_48, 0, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.frame_38)
        self.label_49.setObjectName("label_49")
        self.gridLayout_8.addWidget(self.label_49, 0, 1, 1, 1)
        self.frame_39 = QtWidgets.QFrame(self.frame_38)
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_39)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.tags_yes = QtWidgets.QLineEdit(self.frame_39)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tags_yes.setPalette(palette)
        self.tags_yes.setAutoFillBackground(True)
        self.tags_yes.setFrame(False)
        self.tags_yes.setObjectName("tags_yes")
        self.horizontalLayout_27.addWidget(self.tags_yes)
        self.tags_yes_button = QtWidgets.QToolButton(self.frame_39)
        self.tags_yes_button.setObjectName("tags_yes_button")
        self.horizontalLayout_27.addWidget(self.tags_yes_button)
        self.gridLayout_8.addWidget(self.frame_39, 1, 0, 1, 1)
        self.frame_40 = QtWidgets.QFrame(self.frame_38)
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.tags_no = QtWidgets.QLineEdit(self.frame_40)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tags_no.setPalette(palette)
        self.tags_no.setAutoFillBackground(True)
        self.tags_no.setFrame(False)
        self.tags_no.setObjectName("tags_no")
        self.horizontalLayout_28.addWidget(self.tags_no)
        self.tags_no_button = QtWidgets.QToolButton(self.frame_40)
        self.tags_no_button.setObjectName("tags_no_button")
        self.horizontalLayout_28.addWidget(self.tags_no_button)
        self.gridLayout_8.addWidget(self.frame_40, 1, 1, 1, 1)
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_38)
        self.frame_14 = QtWidgets.QFrame(self.frame_37)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(15)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_31 = QtWidgets.QLabel(self.frame_14)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_14)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 0, 0, 1, 1)
        self.genres_no_list = QtWidgets.QListWidget(self.frame_14)
        self.genres_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.genres_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.genres_no_list.setObjectName("genres_no_list")
        self.gridLayout_4.addWidget(self.genres_no_list, 2, 1, 1, 1)
        self.genres_yes_list = QtWidgets.QListWidget(self.frame_14)
        self.genres_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.genres_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.genres_yes_list.setObjectName("genres_yes_list")
        self.gridLayout_4.addWidget(self.genres_yes_list, 2, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_14)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.genres_yes = QtWidgets.QLineEdit(self.frame_8)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.genres_yes.setPalette(palette)
        self.genres_yes.setAutoFillBackground(True)
        self.genres_yes.setFrame(False)
        self.genres_yes.setObjectName("genres_yes")
        self.horizontalLayout_11.addWidget(self.genres_yes)
        self.genres_yes_button = QtWidgets.QToolButton(self.frame_8)
        self.genres_yes_button.setObjectName("genres_yes_button")
        self.horizontalLayout_11.addWidget(self.genres_yes_button)
        self.gridLayout_4.addWidget(self.frame_8, 1, 0, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.genres_no = QtWidgets.QLineEdit(self.frame_16)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.genres_no.setPalette(palette)
        self.genres_no.setAutoFillBackground(True)
        self.genres_no.setFrame(False)
        self.genres_no.setObjectName("genres_no")
        self.horizontalLayout_12.addWidget(self.genres_no)
        self.genres_no_button = QtWidgets.QToolButton(self.frame_16)
        self.genres_no_button.setObjectName("genres_no_button")
        self.horizontalLayout_12.addWidget(self.genres_no_button)
        self.gridLayout_4.addWidget(self.frame_16, 1, 1, 1, 1)
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame_14)
        self.label_24 = QtWidgets.QLabel(self.frame_37)
        self.label_24.setObjectName("label_24")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.frame_34 = QtWidgets.QFrame(self.frame_37)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_34)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setHorizontalSpacing(15)
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_35 = QtWidgets.QFrame(self.frame_34)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.actors_no = QtWidgets.QLineEdit(self.frame_35)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.actors_no.setPalette(palette)
        self.actors_no.setAutoFillBackground(True)
        self.actors_no.setFrame(False)
        self.actors_no.setObjectName("actors_no")
        self.horizontalLayout_25.addWidget(self.actors_no)
        self.actors_no_button = QtWidgets.QToolButton(self.frame_35)
        self.actors_no_button.setObjectName("actors_no_button")
        self.horizontalLayout_25.addWidget(self.actors_no_button)
        self.gridLayout_7.addWidget(self.frame_35, 1, 1, 1, 1)
        self.frame_36 = QtWidgets.QFrame(self.frame_34)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.actors_yes = QtWidgets.QLineEdit(self.frame_36)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.actors_yes.setPalette(palette)
        self.actors_yes.setAutoFillBackground(True)
        self.actors_yes.setFrame(False)
        self.actors_yes.setObjectName("actors_yes")
        self.horizontalLayout_26.addWidget(self.actors_yes)
        self.actors_yes_button = QtWidgets.QToolButton(self.frame_36)
        self.actors_yes_button.setObjectName("actors_yes_button")
        self.horizontalLayout_26.addWidget(self.actors_yes_button)
        self.gridLayout_7.addWidget(self.frame_36, 1, 0, 1, 1)
        self.actors_no_list = QtWidgets.QListWidget(self.frame_34)
        self.actors_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.actors_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.actors_no_list.setObjectName("actors_no_list")
        self.gridLayout_7.addWidget(self.actors_no_list, 2, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.frame_34)
        self.label_45.setObjectName("label_45")
        self.gridLayout_7.addWidget(self.label_45, 0, 1, 1, 1)
        self.actors_yes_list = QtWidgets.QListWidget(self.frame_34)
        self.actors_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.actors_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.actors_yes_list.setObjectName("actors_yes_list")
        self.gridLayout_7.addWidget(self.actors_yes_list, 2, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.frame_34)
        self.label_46.setObjectName("label_46")
        self.gridLayout_7.addWidget(self.label_46, 0, 0, 1, 1)
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.frame_34)
        self.label_44 = QtWidgets.QLabel(self.frame_37)
        self.label_44.setObjectName("label_44")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.label_5 = QtWidgets.QLabel(self.frame_37)
        self.label_5.setObjectName("label_5")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.frame_41 = QtWidgets.QFrame(self.frame_37)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_41)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setHorizontalSpacing(15)
        self.gridLayout_10.setVerticalSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame_44 = QtWidgets.QFrame(self.frame_41)
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_44)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.series_no = QtWidgets.QLineEdit(self.frame_44)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.series_no.setPalette(palette)
        self.series_no.setAutoFillBackground(True)
        self.series_no.setFrame(False)
        self.series_no.setObjectName("series_no")
        self.horizontalLayout_31.addWidget(self.series_no)
        self.series_no_button = QtWidgets.QToolButton(self.frame_44)
        self.series_no_button.setObjectName("series_no_button")
        self.horizontalLayout_31.addWidget(self.series_no_button)
        self.gridLayout_10.addWidget(self.frame_44, 1, 1, 1, 1)
        self.frame_45 = QtWidgets.QFrame(self.frame_41)
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_45)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.series_yes = QtWidgets.QLineEdit(self.frame_45)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.series_yes.setPalette(palette)
        self.series_yes.setAutoFillBackground(True)
        self.series_yes.setFrame(False)
        self.series_yes.setObjectName("series_yes")
        self.horizontalLayout_32.addWidget(self.series_yes)
        self.series_yes_button = QtWidgets.QToolButton(self.frame_45)
        self.series_yes_button.setObjectName("series_yes_button")
        self.horizontalLayout_32.addWidget(self.series_yes_button)
        self.gridLayout_10.addWidget(self.frame_45, 1, 0, 1, 1)
        self.series_no_list = QtWidgets.QListWidget(self.frame_41)
        self.series_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.series_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.series_no_list.setObjectName("series_no_list")
        self.gridLayout_10.addWidget(self.series_no_list, 2, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.frame_41)
        self.label_52.setObjectName("label_52")
        self.gridLayout_10.addWidget(self.label_52, 0, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.frame_41)
        self.label_53.setObjectName("label_53")
        self.gridLayout_10.addWidget(self.label_53, 0, 0, 1, 1)
        self.series_yes_list = QtWidgets.QListWidget(self.frame_41)
        self.series_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.series_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.series_yes_list.setObjectName("series_yes_list")
        self.gridLayout_10.addWidget(self.series_yes_list, 2, 0, 1, 1)
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.frame_41)
        self.frame_61 = QtWidgets.QFrame(self.frame_37)
        self.frame_61.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_61)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setHorizontalSpacing(15)
        self.gridLayout_16.setVerticalSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.frame_62 = QtWidgets.QFrame(self.frame_61)
        self.frame_62.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_62.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_62.setObjectName("frame_62")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.frame_62)
        self.horizontalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_43.setSpacing(0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.director_no = QtWidgets.QLineEdit(self.frame_62)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.director_no.setPalette(palette)
        self.director_no.setAutoFillBackground(True)
        self.director_no.setFrame(False)
        self.director_no.setObjectName("director_no")
        self.horizontalLayout_43.addWidget(self.director_no)
        self.director_no_button = QtWidgets.QToolButton(self.frame_62)
        self.director_no_button.setObjectName("director_no_button")
        self.horizontalLayout_43.addWidget(self.director_no_button)
        self.gridLayout_16.addWidget(self.frame_62, 1, 1, 1, 1)
        self.frame_63 = QtWidgets.QFrame(self.frame_61)
        self.frame_63.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_63.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_63.setObjectName("frame_63")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout(self.frame_63)
        self.horizontalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_44.setSpacing(0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.director_yes = QtWidgets.QLineEdit(self.frame_63)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.director_yes.setPalette(palette)
        self.director_yes.setAutoFillBackground(True)
        self.director_yes.setFrame(False)
        self.director_yes.setObjectName("director_yes")
        self.horizontalLayout_44.addWidget(self.director_yes)
        self.director_yes_button = QtWidgets.QToolButton(self.frame_63)
        self.director_yes_button.setObjectName("director_yes_button")
        self.horizontalLayout_44.addWidget(self.director_yes_button)
        self.gridLayout_16.addWidget(self.frame_63, 1, 0, 1, 1)
        self.director_no_list = QtWidgets.QListWidget(self.frame_61)
        self.director_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.director_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.director_no_list.setObjectName("director_no_list")
        self.gridLayout_16.addWidget(self.director_no_list, 2, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.frame_61)
        self.label_64.setObjectName("label_64")
        self.gridLayout_16.addWidget(self.label_64, 0, 1, 1, 1)
        self.director_yes_list = QtWidgets.QListWidget(self.frame_61)
        self.director_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.director_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.director_yes_list.setObjectName("director_yes_list")
        self.gridLayout_16.addWidget(self.director_yes_list, 2, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.frame_61)
        self.label_65.setObjectName("label_65")
        self.gridLayout_16.addWidget(self.label_65, 0, 0, 1, 1)
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.frame_61)
        self.label_4 = QtWidgets.QLabel(self.frame_37)
        self.label_4.setObjectName("label_4")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.gridLayout_3.addWidget(self.frame_37, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.delete)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.frame_46 = QtWidgets.QFrame(self.frame_2)
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_46)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setHorizontalSpacing(15)
        self.gridLayout_11.setVerticalSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_47 = QtWidgets.QFrame(self.frame_46)
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_47)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.studio_no = QtWidgets.QLineEdit(self.frame_47)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.studio_no.setPalette(palette)
        self.studio_no.setAutoFillBackground(True)
        self.studio_no.setFrame(False)
        self.studio_no.setObjectName("studio_no")
        self.horizontalLayout_33.addWidget(self.studio_no)
        self.studio_no_button = QtWidgets.QToolButton(self.frame_47)
        self.studio_no_button.setObjectName("studio_no_button")
        self.horizontalLayout_33.addWidget(self.studio_no_button)
        self.gridLayout_11.addWidget(self.frame_47, 1, 1, 1, 1)
        self.frame_48 = QtWidgets.QFrame(self.frame_46)
        self.frame_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_48)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.studio_yes = QtWidgets.QLineEdit(self.frame_48)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.studio_yes.setPalette(palette)
        self.studio_yes.setAutoFillBackground(True)
        self.studio_yes.setFrame(False)
        self.studio_yes.setObjectName("studio_yes")
        self.horizontalLayout_34.addWidget(self.studio_yes)
        self.studio_yes_button = QtWidgets.QToolButton(self.frame_48)
        self.studio_yes_button.setObjectName("studio_yes_button")
        self.horizontalLayout_34.addWidget(self.studio_yes_button)
        self.gridLayout_11.addWidget(self.frame_48, 1, 0, 1, 1)
        self.studio_no_list = QtWidgets.QListWidget(self.frame_46)
        self.studio_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.studio_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.studio_no_list.setObjectName("studio_no_list")
        self.gridLayout_11.addWidget(self.studio_no_list, 2, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.frame_46)
        self.label_54.setObjectName("label_54")
        self.gridLayout_11.addWidget(self.label_54, 0, 1, 1, 1)
        self.studio_yes_list = QtWidgets.QListWidget(self.frame_46)
        self.studio_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.studio_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.studio_yes_list.setObjectName("studio_yes_list")
        self.gridLayout_11.addWidget(self.studio_yes_list, 2, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.frame_46)
        self.label_55.setObjectName("label_55")
        self.gridLayout_11.addWidget(self.label_55, 0, 0, 1, 1)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame_46)
        self.frame_52 = QtWidgets.QFrame(self.frame_2)
        self.frame_52.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_52)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setHorizontalSpacing(15)
        self.gridLayout_13.setVerticalSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_53 = QtWidgets.QFrame(self.frame_52)
        self.frame_53.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frame_53)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setSpacing(0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.media_type_no = QtWidgets.QLineEdit(self.frame_53)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.media_type_no.setPalette(palette)
        self.media_type_no.setAutoFillBackground(True)
        self.media_type_no.setFrame(False)
        self.media_type_no.setObjectName("media_type_no")
        self.horizontalLayout_37.addWidget(self.media_type_no)
        self.media_type_no_button = QtWidgets.QToolButton(self.frame_53)
        self.media_type_no_button.setObjectName("media_type_no_button")
        self.horizontalLayout_37.addWidget(self.media_type_no_button)
        self.gridLayout_13.addWidget(self.frame_53, 1, 1, 1, 1)
        self.frame_54 = QtWidgets.QFrame(self.frame_52)
        self.frame_54.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_54.setObjectName("frame_54")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.frame_54)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setSpacing(0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.media_type_yes = QtWidgets.QLineEdit(self.frame_54)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.media_type_yes.setPalette(palette)
        self.media_type_yes.setAutoFillBackground(True)
        self.media_type_yes.setFrame(False)
        self.media_type_yes.setObjectName("media_type_yes")
        self.horizontalLayout_38.addWidget(self.media_type_yes)
        self.media_types_yes_button = QtWidgets.QToolButton(self.frame_54)
        self.media_types_yes_button.setObjectName("media_types_yes_button")
        self.horizontalLayout_38.addWidget(self.media_types_yes_button)
        self.gridLayout_13.addWidget(self.frame_54, 1, 0, 1, 1)
        self.media_type_no_list = QtWidgets.QListWidget(self.frame_52)
        self.media_type_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.media_type_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.media_type_no_list.setObjectName("media_type_no_list")
        self.gridLayout_13.addWidget(self.media_type_no_list, 2, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.frame_52)
        self.label_58.setObjectName("label_58")
        self.gridLayout_13.addWidget(self.label_58, 0, 1, 1, 1)
        self.media_type_yes_list = QtWidgets.QListWidget(self.frame_52)
        self.media_type_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.media_type_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.media_type_yes_list.setObjectName("media_type_yes_list")
        self.gridLayout_13.addWidget(self.media_type_yes_list, 2, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.frame_52)
        self.label_59.setObjectName("label_59")
        self.gridLayout_13.addWidget(self.label_59, 0, 0, 1, 1)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_52)
        self.frame_55 = QtWidgets.QFrame(self.frame_2)
        self.frame_55.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_55.setObjectName("frame_55")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_55)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setHorizontalSpacing(15)
        self.gridLayout_14.setVerticalSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.frame_56 = QtWidgets.QFrame(self.frame_55)
        self.frame_56.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_56.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_56.setObjectName("frame_56")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.frame_56)
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_39.setSpacing(0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.country_no = QtWidgets.QLineEdit(self.frame_56)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.country_no.setPalette(palette)
        self.country_no.setAutoFillBackground(True)
        self.country_no.setFrame(False)
        self.country_no.setObjectName("country_no")
        self.horizontalLayout_39.addWidget(self.country_no)
        self.country_no_button = QtWidgets.QToolButton(self.frame_56)
        self.country_no_button.setObjectName("country_no_button")
        self.horizontalLayout_39.addWidget(self.country_no_button)
        self.gridLayout_14.addWidget(self.frame_56, 1, 1, 1, 1)
        self.frame_57 = QtWidgets.QFrame(self.frame_55)
        self.frame_57.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_57.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_57.setObjectName("frame_57")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.frame_57)
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_40.setSpacing(0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.country_yes = QtWidgets.QLineEdit(self.frame_57)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.country_yes.setPalette(palette)
        self.country_yes.setAutoFillBackground(True)
        self.country_yes.setFrame(False)
        self.country_yes.setObjectName("country_yes")
        self.horizontalLayout_40.addWidget(self.country_yes)
        self.country_yes_button = QtWidgets.QToolButton(self.frame_57)
        self.country_yes_button.setObjectName("country_yes_button")
        self.horizontalLayout_40.addWidget(self.country_yes_button)
        self.gridLayout_14.addWidget(self.frame_57, 1, 0, 1, 1)
        self.country_no_list = QtWidgets.QListWidget(self.frame_55)
        self.country_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.country_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.country_no_list.setObjectName("country_no_list")
        self.gridLayout_14.addWidget(self.country_no_list, 2, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.frame_55)
        self.label_60.setObjectName("label_60")
        self.gridLayout_14.addWidget(self.label_60, 0, 1, 1, 1)
        self.country_yes_list = QtWidgets.QListWidget(self.frame_55)
        self.country_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.country_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.country_yes_list.setObjectName("country_yes_list")
        self.gridLayout_14.addWidget(self.country_yes_list, 2, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.frame_55)
        self.label_61.setObjectName("label_61")
        self.gridLayout_14.addWidget(self.label_61, 0, 0, 1, 1)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.frame_55)
        self.frame_58 = QtWidgets.QFrame(self.frame_2)
        self.frame_58.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_58.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_58.setObjectName("frame_58")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_58)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setHorizontalSpacing(15)
        self.gridLayout_15.setVerticalSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frame_59 = QtWidgets.QFrame(self.frame_58)
        self.frame_59.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_59.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_59.setObjectName("frame_59")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.frame_59)
        self.horizontalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_41.setSpacing(0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.language_no = QtWidgets.QLineEdit(self.frame_59)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.language_no.setPalette(palette)
        self.language_no.setAutoFillBackground(True)
        self.language_no.setFrame(False)
        self.language_no.setObjectName("language_no")
        self.horizontalLayout_41.addWidget(self.language_no)
        self.language_no_button = QtWidgets.QToolButton(self.frame_59)
        self.language_no_button.setObjectName("language_no_button")
        self.horizontalLayout_41.addWidget(self.language_no_button)
        self.gridLayout_15.addWidget(self.frame_59, 1, 1, 1, 1)
        self.frame_60 = QtWidgets.QFrame(self.frame_58)
        self.frame_60.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_60.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_60.setObjectName("frame_60")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.frame_60)
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_42.setSpacing(0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.language_yes = QtWidgets.QLineEdit(self.frame_60)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.language_yes.setPalette(palette)
        self.language_yes.setAutoFillBackground(True)
        self.language_yes.setFrame(False)
        self.language_yes.setObjectName("language_yes")
        self.horizontalLayout_42.addWidget(self.language_yes)
        self.language_yes_button = QtWidgets.QToolButton(self.frame_60)
        self.language_yes_button.setObjectName("language_yes_button")
        self.horizontalLayout_42.addWidget(self.language_yes_button)
        self.gridLayout_15.addWidget(self.frame_60, 1, 0, 1, 1)
        self.language_no_list = QtWidgets.QListWidget(self.frame_58)
        self.language_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.language_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.language_no_list.setObjectName("language_no_list")
        self.gridLayout_15.addWidget(self.language_no_list, 2, 1, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.frame_58)
        self.label_62.setObjectName("label_62")
        self.gridLayout_15.addWidget(self.label_62, 0, 1, 1, 1)
        self.language_yes_list = QtWidgets.QListWidget(self.frame_58)
        self.language_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.language_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.language_yes_list.setObjectName("language_yes_list")
        self.gridLayout_15.addWidget(self.language_yes_list, 2, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.frame_58)
        self.label_63.setObjectName("label_63")
        self.gridLayout_15.addWidget(self.label_63, 0, 0, 1, 1)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.frame_58)
        self.submit_delete = QtWidgets.QPushButton(self.frame_2)
        self.submit_delete.setMinimumSize(QtCore.QSize(50, 50))
        self.submit_delete.setObjectName("submit_delete")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.submit_delete)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.gridLayout_3.addWidget(self.frame_2, 0, 1, 1, 1)
        self.tab.addTab(self.delete, "")
        self.gridLayout.addWidget(self.tab, 0, 0, 1, 1)
        create_delete_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(create_delete_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 22))
        self.menubar.setObjectName("menubar")
        create_delete_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(create_delete_window)
        self.statusbar.setObjectName("statusbar")
        create_delete_window.setStatusBar(self.statusbar)

        self.retranslateUi(create_delete_window)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(create_delete_window)

    def retranslateUi(self, create_delete_window):
        _translate = QtCore.QCoreApplication.translate
        create_delete_window.setWindowTitle(_translate("create_delete_window", "Create & Delete"))
        self.label_32.setText(_translate("create_delete_window", "Tags"))
        self.label.setText(_translate("create_delete_window", "Genres"))
        self.label_27.setText(_translate("create_delete_window", "Actors"))
        self.label_3.setText(_translate("create_delete_window", "Series"))
        self.label_25.setText(_translate("create_delete_window", "Director"))
        self.label_16.setText(_translate("create_delete_window", "Media Type"))
        self.label_26.setText(_translate("create_delete_window", "Studio"))
        self.submit_create.setText(_translate("create_delete_window", "Submit"))
        self.label_18.setText(_translate("create_delete_window", "Country of \n"
"Origin"))
        self.label_20.setText(_translate("create_delete_window", "Languages"))
        self.tab.setTabText(self.tab.indexOf(self.create), _translate("create_delete_window", "Create"))
        self.label_47.setText(_translate("create_delete_window", "Tags"))
        self.label_48.setText(_translate("create_delete_window", "Keep"))
        self.label_49.setText(_translate("create_delete_window", "Delete"))
        self.tags_yes_button.setText(_translate("create_delete_window", "..."))
        self.tags_no_button.setText(_translate("create_delete_window", "..."))
        self.label_31.setText(_translate("create_delete_window", "Delete"))
        self.label_33.setText(_translate("create_delete_window", "Keep"))
        self.genres_yes_button.setText(_translate("create_delete_window", "..."))
        self.genres_no_button.setText(_translate("create_delete_window", "..."))
        self.label_24.setText(_translate("create_delete_window", "Genres"))
        self.actors_no_button.setText(_translate("create_delete_window", "..."))
        self.actors_yes_button.setText(_translate("create_delete_window", "..."))
        self.label_45.setText(_translate("create_delete_window", "Delete"))
        self.label_46.setText(_translate("create_delete_window", "Keep"))
        self.label_44.setText(_translate("create_delete_window", "Actors"))
        self.label_5.setText(_translate("create_delete_window", "Series"))
        self.series_no_button.setText(_translate("create_delete_window", "..."))
        self.series_yes_button.setText(_translate("create_delete_window", "..."))
        self.label_52.setText(_translate("create_delete_window", "Delete"))
        self.label_53.setText(_translate("create_delete_window", "Keep"))
        self.director_no_button.setText(_translate("create_delete_window", "..."))
        self.director_yes_button.setText(_translate("create_delete_window", "..."))
        self.label_64.setText(_translate("create_delete_window", "Delete"))
        self.label_65.setText(_translate("create_delete_window", "Keep"))
        self.label_4.setText(_translate("create_delete_window", "Director"))
        self.label_2.setText(_translate("create_delete_window", "Studio"))
        self.studio_no_button.setText(_translate("create_delete_window", "..."))
        self.studio_yes_button.setText(_translate("create_delete_window", "..."))
        self.label_54.setText(_translate("create_delete_window", "Delete"))
        self.label_55.setText(_translate("create_delete_window", "Keep"))
        self.media_type_no_button.setText(_translate("create_delete_window", "..."))
        self.media_types_yes_button.setText(_translate("create_delete_window", "..."))
        self.label_58.setText(_translate("create_delete_window", "Delete"))
        self.label_59.setText(_translate("create_delete_window", "Keep"))
        self.country_no_button.setText(_translate("create_delete_window", "..."))
        self.country_yes_button.setText(_translate("create_delete_window", "..."))
        self.label_60.setText(_translate("create_delete_window", "Delete"))
        self.label_61.setText(_translate("create_delete_window", "Keep"))
        self.language_no_button.setText(_translate("create_delete_window", "..."))
        self.language_yes_button.setText(_translate("create_delete_window", "..."))
        self.label_62.setText(_translate("create_delete_window", "Delete"))
        self.label_63.setText(_translate("create_delete_window", "Keep"))
        self.submit_delete.setText(_translate("create_delete_window", "Submit"))
        self.label_6.setText(_translate("create_delete_window", "Media Type"))
        self.label_7.setText(_translate("create_delete_window", "Country of \n"
"Origin"))
        self.label_8.setText(_translate("create_delete_window", "Languages"))
        self.tab.setTabText(self.tab.indexOf(self.delete), _translate("create_delete_window", "Delete"))
