# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_window(object):
    def setupUi(self, edit_window):
        edit_window.setObjectName("edit_window")
        edit_window.resize(1109, 750)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        edit_window.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(edit_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.confirm = QtWidgets.QPushButton(self.centralwidget)
        self.confirm.setMinimumSize(QtCore.QSize(50, 50))
        self.confirm.setMaximumSize(QtCore.QSize(200, 16777215))
        self.confirm.setObjectName("confirm")
        self.gridLayout.addWidget(self.confirm, 3, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.order = QtWidgets.QLineEdit(self.frame_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.order.setPalette(palette)
        self.order.setAutoFillBackground(True)
        self.order.setFrame(False)
        self.order.setObjectName("order")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.order)
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.series_bleh = QtWidgets.QFrame(self.frame_2)
        self.series_bleh.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.series_bleh.setFrameShadow(QtWidgets.QFrame.Raised)
        self.series_bleh.setObjectName("series_bleh")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.series_bleh)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.series = QtWidgets.QLineEdit(self.series_bleh)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.series.setPalette(palette)
        self.series.setAutoFillBackground(True)
        self.series.setFrame(False)
        self.series.setObjectName("series")
        self.verticalLayout.addWidget(self.series)
        self.series_list = QtWidgets.QListWidget(self.series_bleh)
        self.series_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.series_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.series_list.setAlternatingRowColors(False)
        self.series_list.setObjectName("series_list")
        self.verticalLayout.addWidget(self.series_list)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.series_bleh)
        self.frame_18 = QtWidgets.QFrame(self.frame_2)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(15)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.actors_yes = QtWidgets.QLineEdit(self.frame_18)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.actors_yes.setPalette(palette)
        self.actors_yes.setAutoFillBackground(True)
        self.actors_yes.setFrame(False)
        self.actors_yes.setObjectName("actors_yes")
        self.gridLayout_6.addWidget(self.actors_yes, 1, 0, 1, 1)
        self.actors_no = QtWidgets.QLineEdit(self.frame_18)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.actors_no.setPalette(palette)
        self.actors_no.setAutoFillBackground(True)
        self.actors_no.setFrame(False)
        self.actors_no.setObjectName("actors_no")
        self.gridLayout_6.addWidget(self.actors_no, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.frame_18)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 0, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_18)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 0, 0, 1, 1)
        self.actors_yes_list = QtWidgets.QListWidget(self.frame_18)
        self.actors_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.actors_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.actors_yes_list.setObjectName("actors_yes_list")
        self.gridLayout_6.addWidget(self.actors_yes_list, 2, 0, 1, 1)
        self.actors_no_list = QtWidgets.QListWidget(self.frame_18)
        self.actors_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.actors_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.actors_no_list.setObjectName("actors_no_list")
        self.gridLayout_6.addWidget(self.actors_no_list, 2, 1, 1, 1)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.frame_18)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_31 = QtWidgets.QLabel(self.frame_4)
        self.label_31.setObjectName("label_31")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.rating = QtWidgets.QFrame(self.frame_4)
        self.rating.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rating.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rating.setObjectName("rating")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.rating)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_6 = QtWidgets.QFrame(self.rating)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rating_none = QtWidgets.QRadioButton(self.frame_6)
        self.rating_none.setObjectName("rating_none")
        self.horizontalLayout.addWidget(self.rating_none)
        self.rating_1 = QtWidgets.QRadioButton(self.frame_6)
        self.rating_1.setObjectName("rating_1")
        self.horizontalLayout.addWidget(self.rating_1)
        self.rating_2 = QtWidgets.QRadioButton(self.frame_6)
        self.rating_2.setObjectName("rating_2")
        self.horizontalLayout.addWidget(self.rating_2)
        self.rating_3 = QtWidgets.QRadioButton(self.frame_6)
        self.rating_3.setObjectName("rating_3")
        self.horizontalLayout.addWidget(self.rating_3)
        self.rating_4 = QtWidgets.QRadioButton(self.frame_6)
        self.rating_4.setObjectName("rating_4")
        self.horizontalLayout.addWidget(self.rating_4)
        self.rating_5 = QtWidgets.QRadioButton(self.frame_6)
        self.rating_5.setObjectName("rating_5")
        self.horizontalLayout.addWidget(self.rating_5)
        self.horizontalLayout_9.addWidget(self.frame_6)
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rating)
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.media_type = QtWidgets.QComboBox(self.frame_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.media_type.setPalette(palette)
        self.media_type.setAutoFillBackground(True)
        self.media_type.setObjectName("media_type")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.media_type)
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.animated = QtWidgets.QFrame(self.frame_4)
        self.animated.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.animated.setFrameShadow(QtWidgets.QFrame.Raised)
        self.animated.setObjectName("animated")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.animated)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.animated_yes = QtWidgets.QRadioButton(self.animated)
        self.animated_yes.setObjectName("animated_yes")
        self.horizontalLayout_4.addWidget(self.animated_yes)
        self.animated_no = QtWidgets.QRadioButton(self.animated)
        self.animated_no.setObjectName("animated_no")
        self.horizontalLayout_4.addWidget(self.animated_no)
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.animated)
        self.label_26 = QtWidgets.QLabel(self.frame_4)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_25 = QtWidgets.QLabel(self.frame_4)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.series_bleh_2 = QtWidgets.QFrame(self.frame_4)
        self.series_bleh_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.series_bleh_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.series_bleh_2.setObjectName("series_bleh_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.series_bleh_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.studio = QtWidgets.QLineEdit(self.series_bleh_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.studio.setPalette(palette)
        self.studio.setAutoFillBackground(True)
        self.studio.setFrame(False)
        self.studio.setObjectName("studio")
        self.verticalLayout_2.addWidget(self.studio)
        self.studio_list = QtWidgets.QListWidget(self.series_bleh_2)
        self.studio_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.studio_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.studio_list.setAlternatingRowColors(False)
        self.studio_list.setObjectName("studio_list")
        self.verticalLayout_2.addWidget(self.studio_list)
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.series_bleh_2)
        self.series_bleh_3 = QtWidgets.QFrame(self.frame_4)
        self.series_bleh_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.series_bleh_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.series_bleh_3.setObjectName("series_bleh_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.series_bleh_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.director = QtWidgets.QLineEdit(self.series_bleh_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.director.setPalette(palette)
        self.director.setAutoFillBackground(True)
        self.director.setFrame(False)
        self.director.setObjectName("director")
        self.verticalLayout_3.addWidget(self.director)
        self.director_list = QtWidgets.QListWidget(self.series_bleh_3)
        self.director_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.director_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.director_list.setAlternatingRowColors(False)
        self.director_list.setObjectName("director_list")
        self.verticalLayout_3.addWidget(self.director_list)
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.series_bleh_3)
        self.gridLayout.addWidget(self.frame_4, 0, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout.addWidget(self.frame_5, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.title = QtWidgets.QLineEdit(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.title.setPalette(palette)
        self.title.setAutoFillBackground(True)
        self.title.setFrame(False)
        self.title.setObjectName("title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.title)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.alt_title = QtWidgets.QLineEdit(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.alt_title.setPalette(palette)
        self.alt_title.setAutoFillBackground(True)
        self.alt_title.setFrame(False)
        self.alt_title.setObjectName("alt_title")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.alt_title)
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(15)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_29 = QtWidgets.QLabel(self.frame_14)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_14)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 0, 1, 1, 1)
        self.genres_no = QtWidgets.QLineEdit(self.frame_14)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.genres_no.setPalette(palette)
        self.genres_no.setAutoFillBackground(True)
        self.genres_no.setFrame(False)
        self.genres_no.setObjectName("genres_no")
        self.gridLayout_4.addWidget(self.genres_no, 1, 1, 1, 1)
        self.genres_no_list = QtWidgets.QListWidget(self.frame_14)
        self.genres_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.genres_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.genres_no_list.setObjectName("genres_no_list")
        self.gridLayout_4.addWidget(self.genres_no_list, 2, 1, 1, 1)
        self.genres_yes = QtWidgets.QLineEdit(self.frame_14)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.genres_yes.setPalette(palette)
        self.genres_yes.setAutoFillBackground(True)
        self.genres_yes.setFrame(False)
        self.genres_yes.setObjectName("genres_yes")
        self.gridLayout_4.addWidget(self.genres_yes, 1, 0, 1, 1)
        self.genres_yes_list = QtWidgets.QListWidget(self.frame_14)
        self.genres_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.genres_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.genres_yes_list.setObjectName("genres_yes_list")
        self.gridLayout_4.addWidget(self.genres_yes_list, 2, 0, 1, 1)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.frame_14)
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setObjectName("label_32")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.frame_17 = QtWidgets.QFrame(self.frame)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(15)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tags_yes = QtWidgets.QLineEdit(self.frame_17)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tags_yes.setPalette(palette)
        self.tags_yes.setAutoFillBackground(True)
        self.tags_yes.setFrame(False)
        self.tags_yes.setObjectName("tags_yes")
        self.gridLayout_5.addWidget(self.tags_yes, 1, 0, 1, 1)
        self.tags_yes_list = QtWidgets.QListWidget(self.frame_17)
        self.tags_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.tags_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tags_yes_list.setObjectName("tags_yes_list")
        self.gridLayout_5.addWidget(self.tags_yes_list, 2, 0, 1, 1)
        self.tags_no_list = QtWidgets.QListWidget(self.frame_17)
        self.tags_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.tags_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tags_no_list.setObjectName("tags_no_list")
        self.gridLayout_5.addWidget(self.tags_no_list, 2, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_17)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_17)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 0, 1, 1, 1)
        self.tags_no = QtWidgets.QLineEdit(self.frame_17)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tags_no.setPalette(palette)
        self.tags_no.setAutoFillBackground(True)
        self.tags_no.setFrame(False)
        self.tags_no.setObjectName("tags_no")
        self.gridLayout_5.addWidget(self.tags_no, 1, 1, 1, 1)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.frame_17)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.year = QtWidgets.QLineEdit(self.frame_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.year.setPalette(palette)
        self.year.setAutoFillBackground(True)
        self.year.setFrame(False)
        self.year.setObjectName("year")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.year)
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.country = QtWidgets.QComboBox(self.frame_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.country.setPalette(palette)
        self.country.setObjectName("country")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.country)
        self.label_22 = QtWidgets.QLabel(self.frame_3)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.subtitles = QtWidgets.QFrame(self.frame_3)
        self.subtitles.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subtitles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.subtitles.setObjectName("subtitles")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.subtitles)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.subtitles_yes = QtWidgets.QRadioButton(self.subtitles)
        self.subtitles_yes.setObjectName("subtitles_yes")
        self.horizontalLayout_7.addWidget(self.subtitles_yes)
        self.subtitles_no = QtWidgets.QRadioButton(self.subtitles)
        self.subtitles_no.setObjectName("subtitles_no")
        self.horizontalLayout_7.addWidget(self.subtitles_no)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.subtitles)
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.frame_12 = QtWidgets.QFrame(self.frame_3)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.language = QtWidgets.QLineEdit(self.frame_12)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.language.setPalette(palette)
        self.language.setAutoFillBackground(True)
        self.language.setFrame(False)
        self.language.setObjectName("language")
        self.verticalLayout_4.addWidget(self.language)
        self.language_list = QtWidgets.QListWidget(self.frame_12)
        self.language_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.language_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.language_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.language_list.setObjectName("language_list")
        self.verticalLayout_4.addWidget(self.language_list)
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.frame_12)
        self.label_28 = QtWidgets.QLabel(self.frame_3)
        self.label_28.setObjectName("label_28")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.plot = QtWidgets.QTextEdit(self.frame_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.plot.setPalette(palette)
        self.plot.setObjectName("plot")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.plot)
        self.label_35 = QtWidgets.QLabel(self.frame_3)
        self.label_35.setObjectName("label_35")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.notes = QtWidgets.QTextEdit(self.frame_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.notes.setPalette(palette)
        self.notes.setObjectName("notes")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.notes)
        self.gridLayout.addWidget(self.frame_3, 1, 1, 1, 1)
        edit_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(edit_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1109, 22))
        self.menubar.setObjectName("menubar")
        edit_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(edit_window)
        self.statusbar.setObjectName("statusbar")
        edit_window.setStatusBar(self.statusbar)

        self.retranslateUi(edit_window)
        QtCore.QMetaObject.connectSlotsByName(edit_window)

    def retranslateUi(self, edit_window):
        _translate = QtCore.QCoreApplication.translate
        edit_window.setWindowTitle(_translate("edit_window", "Edit"))
        self.confirm.setText(_translate("edit_window", "Confirm"))
        self.label_3.setText(_translate("edit_window", "Series"))
        self.label_4.setText(_translate("edit_window", "Order"))
        self.label_27.setText(_translate("edit_window", "Actors"))
        self.label_36.setText(_translate("edit_window", "Unapplied"))
        self.label_37.setText(_translate("edit_window", "Applied"))
        self.label_31.setText(_translate("edit_window", "Rating"))
        self.rating_none.setText(_translate("edit_window", "None"))
        self.rating_1.setText(_translate("edit_window", "1"))
        self.rating_2.setText(_translate("edit_window", "2"))
        self.rating_3.setText(_translate("edit_window", "3"))
        self.rating_4.setText(_translate("edit_window", "4"))
        self.rating_5.setText(_translate("edit_window", "5"))
        self.label_16.setText(_translate("edit_window", "Media Type"))
        self.label_17.setText(_translate("edit_window", "Animated?"))
        self.animated_yes.setText(_translate("edit_window", "Yes"))
        self.animated_no.setText(_translate("edit_window", "No"))
        self.label_26.setText(_translate("edit_window", "Studio"))
        self.label_25.setText(_translate("edit_window", "Director"))
        self.label.setText(_translate("edit_window", "Title"))
        self.label_2.setText(_translate("edit_window", "Alternate Title"))
        self.label_24.setText(_translate("edit_window", "Genres"))
        self.label_29.setText(_translate("edit_window", "Applied"))
        self.label_30.setText(_translate("edit_window", "Unapplied"))
        self.label_32.setText(_translate("edit_window", "Tags"))
        self.label_34.setText(_translate("edit_window", "Applied"))
        self.label_33.setText(_translate("edit_window", "Unapplied"))
        self.label_23.setText(_translate("edit_window", "Release Year"))
        self.label_18.setText(_translate("edit_window", "Country of Origin"))
        self.label_22.setText(_translate("edit_window", "Subtitles"))
        self.subtitles_yes.setText(_translate("edit_window", "Yes"))
        self.subtitles_no.setText(_translate("edit_window", "No"))
        self.label_20.setText(_translate("edit_window", "Languages"))
        self.label_28.setText(_translate("edit_window", "Plot"))
        self.label_35.setText(_translate("edit_window", "Notes"))
