# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/filter_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filter_window(object):
    def setupUi(self, filter_window):
        filter_window.setObjectName("filter_window")
        filter_window.setWindowModality(QtCore.Qt.ApplicationModal)
        filter_window.resize(1051, 831)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        filter_window.setPalette(palette)
        filter_window.setAutoFillBackground(True)
        filter_window.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(filter_window)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(filter_window)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_16.setPalette(palette)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.frame_52 = QtWidgets.QFrame(self.frame_2)
        self.frame_52.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_52)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setHorizontalSpacing(15)
        self.gridLayout_13.setVerticalSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_53 = QtWidgets.QFrame(self.frame_52)
        self.frame_53.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frame_53)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setSpacing(0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.media_type_no = QtWidgets.QLineEdit(self.frame_53)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.media_type_no.setPalette(palette)
        self.media_type_no.setAutoFillBackground(True)
        self.media_type_no.setFrame(False)
        self.media_type_no.setObjectName("media_type_no")
        self.horizontalLayout_37.addWidget(self.media_type_no)
        self.media_type_no_button = QtWidgets.QToolButton(self.frame_53)
        self.media_type_no_button.setObjectName("media_type_no_button")
        self.horizontalLayout_37.addWidget(self.media_type_no_button)
        self.gridLayout_13.addWidget(self.frame_53, 1, 1, 1, 1)
        self.frame_54 = QtWidgets.QFrame(self.frame_52)
        self.frame_54.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_54.setObjectName("frame_54")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.frame_54)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setSpacing(0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.media_type_yes = QtWidgets.QLineEdit(self.frame_54)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.media_type_yes.setPalette(palette)
        self.media_type_yes.setAutoFillBackground(True)
        self.media_type_yes.setFrame(False)
        self.media_type_yes.setObjectName("media_type_yes")
        self.horizontalLayout_38.addWidget(self.media_type_yes)
        self.media_type_yes_button = QtWidgets.QToolButton(self.frame_54)
        self.media_type_yes_button.setObjectName("media_type_yes_button")
        self.horizontalLayout_38.addWidget(self.media_type_yes_button)
        self.gridLayout_13.addWidget(self.frame_54, 1, 0, 1, 1)
        self.media_type_no_list = QtWidgets.QListWidget(self.frame_52)
        self.media_type_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.media_type_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.media_type_no_list.setObjectName("media_type_no_list")
        self.gridLayout_13.addWidget(self.media_type_no_list, 2, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.frame_52)
        self.label_58.setObjectName("label_58")
        self.gridLayout_13.addWidget(self.label_58, 0, 1, 1, 1)
        self.media_type_yes_list = QtWidgets.QListWidget(self.frame_52)
        self.media_type_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.media_type_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.media_type_yes_list.setObjectName("media_type_yes_list")
        self.gridLayout_13.addWidget(self.media_type_yes_list, 2, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.frame_52)
        self.label_59.setObjectName("label_59")
        self.gridLayout_13.addWidget(self.label_59, 0, 0, 1, 1)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame_52)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_18.setPalette(palette)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.frame_55 = QtWidgets.QFrame(self.frame_2)
        self.frame_55.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_55.setObjectName("frame_55")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_55)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setHorizontalSpacing(15)
        self.gridLayout_14.setVerticalSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.frame_56 = QtWidgets.QFrame(self.frame_55)
        self.frame_56.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_56.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_56.setObjectName("frame_56")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.frame_56)
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_39.setSpacing(0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.country_no = QtWidgets.QLineEdit(self.frame_56)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.country_no.setPalette(palette)
        self.country_no.setAutoFillBackground(True)
        self.country_no.setFrame(False)
        self.country_no.setObjectName("country_no")
        self.horizontalLayout_39.addWidget(self.country_no)
        self.country_no_button = QtWidgets.QToolButton(self.frame_56)
        self.country_no_button.setObjectName("country_no_button")
        self.horizontalLayout_39.addWidget(self.country_no_button)
        self.gridLayout_14.addWidget(self.frame_56, 1, 1, 1, 1)
        self.frame_57 = QtWidgets.QFrame(self.frame_55)
        self.frame_57.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_57.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_57.setObjectName("frame_57")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.frame_57)
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_40.setSpacing(0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.country_yes = QtWidgets.QLineEdit(self.frame_57)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.country_yes.setPalette(palette)
        self.country_yes.setAutoFillBackground(True)
        self.country_yes.setFrame(False)
        self.country_yes.setObjectName("country_yes")
        self.horizontalLayout_40.addWidget(self.country_yes)
        self.country_yes_button = QtWidgets.QToolButton(self.frame_57)
        self.country_yes_button.setObjectName("country_yes_button")
        self.horizontalLayout_40.addWidget(self.country_yes_button)
        self.gridLayout_14.addWidget(self.frame_57, 1, 0, 1, 1)
        self.country_no_list = QtWidgets.QListWidget(self.frame_55)
        self.country_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.country_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.country_no_list.setObjectName("country_no_list")
        self.gridLayout_14.addWidget(self.country_no_list, 2, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.frame_55)
        self.label_60.setObjectName("label_60")
        self.gridLayout_14.addWidget(self.label_60, 0, 1, 1, 1)
        self.country_yes_list = QtWidgets.QListWidget(self.frame_55)
        self.country_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.country_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.country_yes_list.setObjectName("country_yes_list")
        self.gridLayout_14.addWidget(self.country_yes_list, 2, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.frame_55)
        self.label_61.setObjectName("label_61")
        self.gridLayout_14.addWidget(self.label_61, 0, 0, 1, 1)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_55)
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.frame_58 = QtWidgets.QFrame(self.frame_2)
        self.frame_58.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_58.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_58.setObjectName("frame_58")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_58)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setHorizontalSpacing(15)
        self.gridLayout_15.setVerticalSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frame_59 = QtWidgets.QFrame(self.frame_58)
        self.frame_59.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_59.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_59.setObjectName("frame_59")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.frame_59)
        self.horizontalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_41.setSpacing(0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.language_no = QtWidgets.QLineEdit(self.frame_59)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.language_no.setPalette(palette)
        self.language_no.setAutoFillBackground(True)
        self.language_no.setFrame(False)
        self.language_no.setObjectName("language_no")
        self.horizontalLayout_41.addWidget(self.language_no)
        self.language_no_button = QtWidgets.QToolButton(self.frame_59)
        self.language_no_button.setObjectName("language_no_button")
        self.horizontalLayout_41.addWidget(self.language_no_button)
        self.gridLayout_15.addWidget(self.frame_59, 1, 1, 1, 1)
        self.frame_60 = QtWidgets.QFrame(self.frame_58)
        self.frame_60.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_60.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_60.setObjectName("frame_60")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.frame_60)
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_42.setSpacing(0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.language_yes = QtWidgets.QLineEdit(self.frame_60)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.language_yes.setPalette(palette)
        self.language_yes.setAutoFillBackground(True)
        self.language_yes.setFrame(False)
        self.language_yes.setObjectName("language_yes")
        self.horizontalLayout_42.addWidget(self.language_yes)
        self.language_yes_button = QtWidgets.QToolButton(self.frame_60)
        self.language_yes_button.setObjectName("language_yes_button")
        self.horizontalLayout_42.addWidget(self.language_yes_button)
        self.gridLayout_15.addWidget(self.frame_60, 1, 0, 1, 1)
        self.language_no_list = QtWidgets.QListWidget(self.frame_58)
        self.language_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.language_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.language_no_list.setObjectName("language_no_list")
        self.gridLayout_15.addWidget(self.language_no_list, 2, 1, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.frame_58)
        self.label_62.setObjectName("label_62")
        self.gridLayout_15.addWidget(self.label_62, 0, 1, 1, 1)
        self.language_yes_list = QtWidgets.QListWidget(self.frame_58)
        self.language_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.language_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.language_yes_list.setObjectName("language_yes_list")
        self.gridLayout_15.addWidget(self.language_yes_list, 2, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.frame_58)
        self.label_63.setObjectName("label_63")
        self.gridLayout_15.addWidget(self.label_63, 0, 0, 1, 1)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.frame_58)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(filter_window)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_3.setVerticalSpacing(20)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_31 = QtWidgets.QLabel(self.frame_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_31.setPalette(palette)
        self.label_31.setObjectName("label_31")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rating_none = QtWidgets.QCheckBox(self.frame_6)
        self.rating_none.setObjectName("rating_none")
        self.horizontalLayout.addWidget(self.rating_none)
        self.rating_1 = QtWidgets.QCheckBox(self.frame_6)
        self.rating_1.setObjectName("rating_1")
        self.horizontalLayout.addWidget(self.rating_1)
        self.rating_2 = QtWidgets.QCheckBox(self.frame_6)
        self.rating_2.setObjectName("rating_2")
        self.horizontalLayout.addWidget(self.rating_2)
        self.rating_3 = QtWidgets.QCheckBox(self.frame_6)
        self.rating_3.setObjectName("rating_3")
        self.horizontalLayout.addWidget(self.rating_3)
        self.rating_4 = QtWidgets.QCheckBox(self.frame_6)
        self.rating_4.setObjectName("rating_4")
        self.horizontalLayout.addWidget(self.rating_4)
        self.rating_5 = QtWidgets.QCheckBox(self.frame_6)
        self.rating_5.setObjectName("rating_5")
        self.horizontalLayout.addWidget(self.rating_5)
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame_6)
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_23.setPalette(palette)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.frame_25 = QtWidgets.QFrame(self.frame_3)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.year_less = QtWidgets.QRadioButton(self.frame_25)
        self.year_less.setObjectName("year_less")
        self.horizontalLayout_17.addWidget(self.year_less)
        self.year_greater = QtWidgets.QRadioButton(self.frame_25)
        self.year_greater.setObjectName("year_greater")
        self.horizontalLayout_17.addWidget(self.year_greater)
        self.year_equals = QtWidgets.QRadioButton(self.frame_25)
        self.year_equals.setObjectName("year_equals")
        self.horizontalLayout_17.addWidget(self.year_equals)
        self.year = QtWidgets.QLineEdit(self.frame_25)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.year.setPalette(palette)
        self.year.setAutoFillBackground(True)
        self.year.setFrame(False)
        self.year.setObjectName("year")
        self.horizontalLayout_17.addWidget(self.year)
        self.year_button = QtWidgets.QToolButton(self.frame_25)
        self.year_button.setObjectName("year_button")
        self.horizontalLayout_17.addWidget(self.year_button)
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_25)
        self.label_22 = QtWidgets.QLabel(self.frame_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_22.setPalette(palette)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.subtitles = QtWidgets.QFrame(self.frame_3)
        self.subtitles.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subtitles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.subtitles.setObjectName("subtitles")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.subtitles)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.subtitles_yes = QtWidgets.QRadioButton(self.subtitles)
        self.subtitles_yes.setObjectName("subtitles_yes")
        self.horizontalLayout_7.addWidget(self.subtitles_yes)
        self.subtitles_no = QtWidgets.QRadioButton(self.subtitles)
        self.subtitles_no.setObjectName("subtitles_no")
        self.horizontalLayout_7.addWidget(self.subtitles_no)
        self.subtitles_button = QtWidgets.QToolButton(self.subtitles)
        self.subtitles_button.setObjectName("subtitles_button")
        self.horizontalLayout_7.addWidget(self.subtitles_button)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.subtitles)
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_17.setPalette(palette)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.animated = QtWidgets.QFrame(self.frame_3)
        self.animated.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.animated.setFrameShadow(QtWidgets.QFrame.Raised)
        self.animated.setObjectName("animated")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.animated)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.animated_yes = QtWidgets.QRadioButton(self.animated)
        self.animated_yes.setObjectName("animated_yes")
        self.horizontalLayout_4.addWidget(self.animated_yes)
        self.animated_no = QtWidgets.QRadioButton(self.animated)
        self.animated_no.setObjectName("animated_no")
        self.horizontalLayout_4.addWidget(self.animated_no)
        self.animated_button = QtWidgets.QToolButton(self.animated)
        self.animated_button.setObjectName("animated_button")
        self.horizontalLayout_4.addWidget(self.animated_button)
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.animated)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser.setObjectName("textBrowser")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.textBrowser)
        self.submit = QtWidgets.QPushButton(self.frame_3)
        self.submit.setMinimumSize(QtCore.QSize(50, 50))
        self.submit.setStyleSheet("background:rgb(0, 255, 0);")
        self.submit.setAutoDefault(False)
        self.submit.setObjectName("submit")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.submit)
        self.gridLayout.addWidget(self.frame_3, 2, 1, 1, 1)
        self.frame = QtWidgets.QFrame(filter_window)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setObjectName("label_32")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.frame_17 = QtWidgets.QFrame(self.frame)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(15)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_34 = QtWidgets.QLabel(self.frame_17)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 0, 0, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.frame_17)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tags_yes = QtWidgets.QLineEdit(self.frame_16)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tags_yes.setPalette(palette)
        self.tags_yes.setAutoFillBackground(True)
        self.tags_yes.setFrame(False)
        self.tags_yes.setObjectName("tags_yes")
        self.horizontalLayout_13.addWidget(self.tags_yes)
        self.tags_yes_button = QtWidgets.QToolButton(self.frame_16)
        self.tags_yes_button.setObjectName("tags_yes_button")
        self.horizontalLayout_13.addWidget(self.tags_yes_button)
        self.gridLayout_5.addWidget(self.frame_16, 1, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tags_no = QtWidgets.QLineEdit(self.frame_19)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tags_no.setPalette(palette)
        self.tags_no.setAutoFillBackground(True)
        self.tags_no.setFrame(False)
        self.tags_no.setObjectName("tags_no")
        self.horizontalLayout_14.addWidget(self.tags_no)
        self.tags_no_button = QtWidgets.QToolButton(self.frame_19)
        self.tags_no_button.setObjectName("tags_no_button")
        self.horizontalLayout_14.addWidget(self.tags_no_button)
        self.gridLayout_5.addWidget(self.frame_19, 1, 1, 1, 1)
        self.tags_yes_list = QtWidgets.QListWidget(self.frame_17)
        self.tags_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.tags_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tags_yes_list.setObjectName("tags_yes_list")
        self.gridLayout_5.addWidget(self.tags_yes_list, 2, 0, 1, 1)
        self.tags_no_list = QtWidgets.QListWidget(self.frame_17)
        self.tags_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.tags_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tags_no_list.setObjectName("tags_no_list")
        self.gridLayout_5.addWidget(self.tags_no_list, 2, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_17)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 0, 1, 1, 1)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_17)
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(15)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_30 = QtWidgets.QLabel(self.frame_14)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 0, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_14)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 0, 0, 1, 1)
        self.genres_no_list = QtWidgets.QListWidget(self.frame_14)
        self.genres_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.genres_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.genres_no_list.setObjectName("genres_no_list")
        self.gridLayout_4.addWidget(self.genres_no_list, 2, 1, 1, 1)
        self.genres_yes_list = QtWidgets.QListWidget(self.frame_14)
        self.genres_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.genres_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.genres_yes_list.setObjectName("genres_yes_list")
        self.gridLayout_4.addWidget(self.genres_yes_list, 2, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_14)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.genres_yes = QtWidgets.QLineEdit(self.frame_7)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.genres_yes.setPalette(palette)
        self.genres_yes.setAutoFillBackground(True)
        self.genres_yes.setFrame(False)
        self.genres_yes.setObjectName("genres_yes")
        self.horizontalLayout_11.addWidget(self.genres_yes)
        self.genres_yes_button = QtWidgets.QToolButton(self.frame_7)
        self.genres_yes_button.setObjectName("genres_yes_button")
        self.horizontalLayout_11.addWidget(self.genres_yes_button)
        self.gridLayout_4.addWidget(self.frame_7, 1, 0, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.genres_no = QtWidgets.QLineEdit(self.frame_15)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.genres_no.setPalette(palette)
        self.genres_no.setAutoFillBackground(True)
        self.genres_no.setFrame(False)
        self.genres_no.setObjectName("genres_no")
        self.horizontalLayout_12.addWidget(self.genres_no)
        self.genres_no_button = QtWidgets.QToolButton(self.frame_15)
        self.genres_no_button.setObjectName("genres_no_button")
        self.horizontalLayout_12.addWidget(self.genres_no_button)
        self.gridLayout_4.addWidget(self.frame_15, 1, 1, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame_14)
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.frame_18 = QtWidgets.QFrame(self.frame)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(15)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_21 = QtWidgets.QFrame(self.frame_18)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.actors_no = QtWidgets.QLineEdit(self.frame_21)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.actors_no.setPalette(palette)
        self.actors_no.setAutoFillBackground(True)
        self.actors_no.setFrame(False)
        self.actors_no.setObjectName("actors_no")
        self.horizontalLayout_16.addWidget(self.actors_no)
        self.actors_no_button = QtWidgets.QToolButton(self.frame_21)
        self.actors_no_button.setObjectName("actors_no_button")
        self.horizontalLayout_16.addWidget(self.actors_no_button)
        self.gridLayout_6.addWidget(self.frame_21, 1, 1, 1, 1)
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.actors_yes = QtWidgets.QLineEdit(self.frame_20)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.actors_yes.setPalette(palette)
        self.actors_yes.setAutoFillBackground(True)
        self.actors_yes.setFrame(False)
        self.actors_yes.setObjectName("actors_yes")
        self.horizontalLayout_15.addWidget(self.actors_yes)
        self.actors_yes_button = QtWidgets.QToolButton(self.frame_20)
        self.actors_yes_button.setObjectName("actors_yes_button")
        self.horizontalLayout_15.addWidget(self.actors_yes_button)
        self.gridLayout_6.addWidget(self.frame_20, 1, 0, 1, 1)
        self.actors_no_list = QtWidgets.QListWidget(self.frame_18)
        self.actors_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.actors_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.actors_no_list.setObjectName("actors_no_list")
        self.gridLayout_6.addWidget(self.actors_no_list, 2, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.frame_18)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 0, 1, 1, 1)
        self.actors_yes_list = QtWidgets.QListWidget(self.frame_18)
        self.actors_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.actors_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.actors_yes_list.setObjectName("actors_yes_list")
        self.gridLayout_6.addWidget(self.actors_yes_list, 2, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_18)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 0, 0, 1, 1)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.frame_18)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(filter_window)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.rating = QtWidgets.QFrame(self.frame_4)
        self.rating.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rating.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rating.setObjectName("rating")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.rating)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rating)
        self.label_26 = QtWidgets.QLabel(self.frame_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_26.setPalette(palette)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.series_bleh_2 = QtWidgets.QFrame(self.frame_4)
        self.series_bleh_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.series_bleh_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.series_bleh_2.setObjectName("series_bleh_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.series_bleh_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_46 = QtWidgets.QFrame(self.series_bleh_2)
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_46)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setHorizontalSpacing(15)
        self.gridLayout_11.setVerticalSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_47 = QtWidgets.QFrame(self.frame_46)
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_47)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.studio_no = QtWidgets.QLineEdit(self.frame_47)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.studio_no.setPalette(palette)
        self.studio_no.setAutoFillBackground(True)
        self.studio_no.setFrame(False)
        self.studio_no.setObjectName("studio_no")
        self.horizontalLayout_33.addWidget(self.studio_no)
        self.studio_no_button = QtWidgets.QToolButton(self.frame_47)
        self.studio_no_button.setObjectName("studio_no_button")
        self.horizontalLayout_33.addWidget(self.studio_no_button)
        self.gridLayout_11.addWidget(self.frame_47, 1, 1, 1, 1)
        self.frame_48 = QtWidgets.QFrame(self.frame_46)
        self.frame_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_48)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.studio_yes = QtWidgets.QLineEdit(self.frame_48)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.studio_yes.setPalette(palette)
        self.studio_yes.setAutoFillBackground(True)
        self.studio_yes.setFrame(False)
        self.studio_yes.setObjectName("studio_yes")
        self.horizontalLayout_34.addWidget(self.studio_yes)
        self.studio_yes_button = QtWidgets.QToolButton(self.frame_48)
        self.studio_yes_button.setObjectName("studio_yes_button")
        self.horizontalLayout_34.addWidget(self.studio_yes_button)
        self.gridLayout_11.addWidget(self.frame_48, 1, 0, 1, 1)
        self.studio_no_list = QtWidgets.QListWidget(self.frame_46)
        self.studio_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.studio_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.studio_no_list.setObjectName("studio_no_list")
        self.gridLayout_11.addWidget(self.studio_no_list, 2, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.frame_46)
        self.label_54.setObjectName("label_54")
        self.gridLayout_11.addWidget(self.label_54, 0, 1, 1, 1)
        self.studio_yes_list = QtWidgets.QListWidget(self.frame_46)
        self.studio_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.studio_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.studio_yes_list.setObjectName("studio_yes_list")
        self.gridLayout_11.addWidget(self.studio_yes_list, 2, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.frame_46)
        self.label_55.setObjectName("label_55")
        self.gridLayout_11.addWidget(self.label_55, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_46)
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.series_bleh_2)
        self.label_25 = QtWidgets.QLabel(self.frame_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_25.setPalette(palette)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.frame_61 = QtWidgets.QFrame(self.frame_4)
        self.frame_61.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_61)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setHorizontalSpacing(15)
        self.gridLayout_16.setVerticalSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.frame_62 = QtWidgets.QFrame(self.frame_61)
        self.frame_62.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_62.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_62.setObjectName("frame_62")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.frame_62)
        self.horizontalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_43.setSpacing(0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.director_no = QtWidgets.QLineEdit(self.frame_62)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.director_no.setPalette(palette)
        self.director_no.setAutoFillBackground(True)
        self.director_no.setFrame(False)
        self.director_no.setObjectName("director_no")
        self.horizontalLayout_43.addWidget(self.director_no)
        self.director_no_button = QtWidgets.QToolButton(self.frame_62)
        self.director_no_button.setObjectName("director_no_button")
        self.horizontalLayout_43.addWidget(self.director_no_button)
        self.gridLayout_16.addWidget(self.frame_62, 1, 1, 1, 1)
        self.frame_63 = QtWidgets.QFrame(self.frame_61)
        self.frame_63.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_63.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_63.setObjectName("frame_63")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout(self.frame_63)
        self.horizontalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_44.setSpacing(0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.director_yes = QtWidgets.QLineEdit(self.frame_63)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.director_yes.setPalette(palette)
        self.director_yes.setAutoFillBackground(True)
        self.director_yes.setFrame(False)
        self.director_yes.setObjectName("director_yes")
        self.horizontalLayout_44.addWidget(self.director_yes)
        self.director_yes_button = QtWidgets.QToolButton(self.frame_63)
        self.director_yes_button.setObjectName("director_yes_button")
        self.horizontalLayout_44.addWidget(self.director_yes_button)
        self.gridLayout_16.addWidget(self.frame_63, 1, 0, 1, 1)
        self.director_no_list = QtWidgets.QListWidget(self.frame_61)
        self.director_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.director_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.director_no_list.setObjectName("director_no_list")
        self.gridLayout_16.addWidget(self.director_no_list, 2, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.frame_61)
        self.label_64.setObjectName("label_64")
        self.gridLayout_16.addWidget(self.label_64, 0, 1, 1, 1)
        self.director_yes_list = QtWidgets.QListWidget(self.frame_61)
        self.director_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.director_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.director_yes_list.setObjectName("director_yes_list")
        self.gridLayout_16.addWidget(self.director_yes_list, 2, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.frame_61)
        self.label_65.setObjectName("label_65")
        self.gridLayout_16.addWidget(self.label_65, 0, 0, 1, 1)
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.frame_61)
        self.frame_41 = QtWidgets.QFrame(self.frame_4)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_41)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setHorizontalSpacing(15)
        self.gridLayout_10.setVerticalSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame_44 = QtWidgets.QFrame(self.frame_41)
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_44)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.series_no = QtWidgets.QLineEdit(self.frame_44)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.series_no.setPalette(palette)
        self.series_no.setAutoFillBackground(True)
        self.series_no.setFrame(False)
        self.series_no.setObjectName("series_no")
        self.horizontalLayout_31.addWidget(self.series_no)
        self.series_no_button = QtWidgets.QToolButton(self.frame_44)
        self.series_no_button.setObjectName("series_no_button")
        self.horizontalLayout_31.addWidget(self.series_no_button)
        self.gridLayout_10.addWidget(self.frame_44, 1, 1, 1, 1)
        self.frame_45 = QtWidgets.QFrame(self.frame_41)
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_45)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.series_yes = QtWidgets.QLineEdit(self.frame_45)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.series_yes.setPalette(palette)
        self.series_yes.setAutoFillBackground(True)
        self.series_yes.setFrame(False)
        self.series_yes.setObjectName("series_yes")
        self.horizontalLayout_32.addWidget(self.series_yes)
        self.series_yes_button = QtWidgets.QToolButton(self.frame_45)
        self.series_yes_button.setObjectName("series_yes_button")
        self.horizontalLayout_32.addWidget(self.series_yes_button)
        self.gridLayout_10.addWidget(self.frame_45, 1, 0, 1, 1)
        self.series_no_list = QtWidgets.QListWidget(self.frame_41)
        self.series_no_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.series_no_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.series_no_list.setObjectName("series_no_list")
        self.gridLayout_10.addWidget(self.series_no_list, 2, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.frame_41)
        self.label_52.setObjectName("label_52")
        self.gridLayout_10.addWidget(self.label_52, 0, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.frame_41)
        self.label_53.setObjectName("label_53")
        self.gridLayout_10.addWidget(self.label_53, 0, 0, 1, 1)
        self.series_yes_list = QtWidgets.QListWidget(self.frame_41)
        self.series_yes_list.setStyleSheet("QListWidget{background:rgb(120,120,120)}\n"
"QListWidget::item:selected{background: rgb(219, 219, 219)}\n"
"QListWidget::item:selected{color:black} ")
        self.series_yes_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.series_yes_list.setObjectName("series_yes_list")
        self.gridLayout_10.addWidget(self.series_yes_list, 2, 0, 1, 1)
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_41)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.gridLayout.addWidget(self.frame_4, 1, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(filter_window)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.and_filter = QtWidgets.QRadioButton(self.frame_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.and_filter.setPalette(palette)
        self.and_filter.setChecked(True)
        self.and_filter.setObjectName("and_filter")
        self.horizontalLayout_2.addWidget(self.and_filter)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_5)
        self.textBrowser_2.setMaximumSize(QtCore.QSize(16777215, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowser_2.setPalette(palette)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.horizontalLayout_2.addWidget(self.textBrowser_2)
        self.not_filter = QtWidgets.QRadioButton(self.frame_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.not_filter.setPalette(palette)
        self.not_filter.setObjectName("not_filter")
        self.horizontalLayout_2.addWidget(self.not_filter)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_5)
        self.textBrowser_3.setMaximumSize(QtCore.QSize(16777215, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowser_3.setPalette(palette)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.horizontalLayout_2.addWidget(self.textBrowser_3)
        self.or_filter = QtWidgets.QRadioButton(self.frame_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.or_filter.setPalette(palette)
        self.or_filter.setObjectName("or_filter")
        self.horizontalLayout_2.addWidget(self.or_filter)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.frame_5)
        self.textBrowser_4.setMaximumSize(QtCore.QSize(16777215, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowser_4.setPalette(palette)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.horizontalLayout_2.addWidget(self.textBrowser_4)
        self.gridLayout.addWidget(self.frame_5, 0, 0, 1, 2)

        self.retranslateUi(filter_window)
        QtCore.QMetaObject.connectSlotsByName(filter_window)

    def retranslateUi(self, filter_window):
        _translate = QtCore.QCoreApplication.translate
        filter_window.setWindowTitle(_translate("filter_window", "Filter"))
        self.label_16.setText(_translate("filter_window", "Media Type"))
        self.media_type_no_button.setText(_translate("filter_window", "..."))
        self.media_type_yes_button.setText(_translate("filter_window", "..."))
        self.label_58.setText(_translate("filter_window", "All"))
        self.label_59.setText(_translate("filter_window", "Filter"))
        self.label_18.setText(_translate("filter_window", "Country of \n"
"Origin"))
        self.country_no_button.setText(_translate("filter_window", "..."))
        self.country_yes_button.setText(_translate("filter_window", "..."))
        self.label_60.setText(_translate("filter_window", "All"))
        self.label_61.setText(_translate("filter_window", "Filter"))
        self.label_20.setText(_translate("filter_window", "Languages"))
        self.language_no_button.setText(_translate("filter_window", "..."))
        self.language_yes_button.setText(_translate("filter_window", "..."))
        self.label_62.setText(_translate("filter_window", "All"))
        self.label_63.setText(_translate("filter_window", "Filter"))
        self.label_31.setText(_translate("filter_window", "Rating"))
        self.rating_none.setText(_translate("filter_window", "None"))
        self.rating_1.setText(_translate("filter_window", "1"))
        self.rating_2.setText(_translate("filter_window", "2"))
        self.rating_3.setText(_translate("filter_window", "3"))
        self.rating_4.setText(_translate("filter_window", "4"))
        self.rating_5.setText(_translate("filter_window", "5"))
        self.label_23.setText(_translate("filter_window", "Release \n"
"Year"))
        self.year_less.setText(_translate("filter_window", "<"))
        self.year_greater.setText(_translate("filter_window", ">"))
        self.year_equals.setText(_translate("filter_window", "="))
        self.year_button.setText(_translate("filter_window", "..."))
        self.label_22.setText(_translate("filter_window", "Subtitles"))
        self.subtitles_yes.setText(_translate("filter_window", "Yes"))
        self.subtitles_no.setText(_translate("filter_window", "No"))
        self.subtitles_button.setText(_translate("filter_window", "..."))
        self.label_17.setText(_translate("filter_window", "Animated?"))
        self.animated_yes.setText(_translate("filter_window", "Yes"))
        self.animated_no.setText(_translate("filter_window", "No"))
        self.animated_button.setText(_translate("filter_window", "..."))
        self.textBrowser.setHtml(_translate("filter_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Fields in <span style=\" color:#00ffff;\">blue </span><span style=\" color:#000000;\">are forced into OR filtering</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">Fields in </span><span style=\" color:#00ff00;\">green </span><span style=\" color:#000000;\">are forced into AND filtering</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">All other fields can allow you to decide between AND, NOT, OR filtering</span></p></body></html>"))
        self.submit.setText(_translate("filter_window", "Filter"))
        self.label_24.setText(_translate("filter_window", "Genres"))
        self.label_32.setText(_translate("filter_window", "Tags"))
        self.label_34.setText(_translate("filter_window", "Filter"))
        self.tags_yes_button.setText(_translate("filter_window", "..."))
        self.tags_no_button.setText(_translate("filter_window", "..."))
        self.label_33.setText(_translate("filter_window", "All"))
        self.label_30.setText(_translate("filter_window", "All"))
        self.label_29.setText(_translate("filter_window", "Filter"))
        self.genres_yes_button.setText(_translate("filter_window", "..."))
        self.genres_no_button.setText(_translate("filter_window", "..."))
        self.label_27.setText(_translate("filter_window", "Actors"))
        self.actors_no_button.setText(_translate("filter_window", "..."))
        self.actors_yes_button.setText(_translate("filter_window", "..."))
        self.label_36.setText(_translate("filter_window", "All"))
        self.label_37.setText(_translate("filter_window", "Filter"))
        self.label_26.setText(_translate("filter_window", "Studio"))
        self.studio_no_button.setText(_translate("filter_window", "..."))
        self.studio_yes_button.setText(_translate("filter_window", "..."))
        self.label_54.setText(_translate("filter_window", "All"))
        self.label_55.setText(_translate("filter_window", "Filter"))
        self.label_25.setText(_translate("filter_window", "Director"))
        self.director_no_button.setText(_translate("filter_window", "..."))
        self.director_yes_button.setText(_translate("filter_window", "..."))
        self.label_64.setText(_translate("filter_window", "All"))
        self.label_65.setText(_translate("filter_window", "Filter"))
        self.series_no_button.setText(_translate("filter_window", "..."))
        self.series_yes_button.setText(_translate("filter_window", "..."))
        self.label_52.setText(_translate("filter_window", "All"))
        self.label_53.setText(_translate("filter_window", "Filter"))
        self.label_3.setText(_translate("filter_window", "Series"))
        self.and_filter.setText(_translate("filter_window", "AND"))
        self.textBrowser_2.setHtml(_translate("filter_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">searches must include these filters</p></body></html>"))
        self.not_filter.setText(_translate("filter_window", "NOT"))
        self.textBrowser_3.setHtml(_translate("filter_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">searches cannot have these filters</p></body></html>"))
        self.or_filter.setText(_translate("filter_window", "OR"))
        self.textBrowser_4.setHtml(_translate("filter_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">searches must have at least one of these filters</p></body></html>"))
